export interface CardData {
  title: string;
}

export const DECK_OF_ILLUSIONS: CardData[] = [
  { title: 'Red Dragon' },
  { title: 'Knight and Four Guards' },
  { title: 'Succubus or Incubus' },
  { title: 'Druid' },
  { title: 'Cloud Giant' },
  { title: 'Ettin' },
  { title: 'Bugbear' },
  { title: 'Goblin' },
  { title: 'Beholder' },
  { title: 'Archmage and Mage Apprentice' },
  { title: 'Night Hag' },
  { title: 'Assassin' },
  { title: 'Fire Giant' },
  { title: 'Ogre Mage' },
  { title: 'Gnoll' },
  { title: 'Kobold' },
  { title: 'Lich' },
  { title: 'Priest and Two Acolytes' },
  { title: 'Medusa' },
  { title: 'Veteran' },
  { title: 'Frost Giant' },
  { title: 'Troll' },
  { title: 'Hobgoblin' },
  { title: 'Orc' },
  { title: 'Kobold' },
  { title: 'Iron Golem' },
  { title: 'Bandit Captain and Three Bandits' },
  { title: 'Erinyes' },
  { title: 'Berserker' },
  { title: 'Hill Giant' },
  { title: 'Ogre' },
  { title: 'Kobold' },
  { title: 'You (the deck\'s owner' },
  { title: 'You (the deck\'s owner' }
];
